services:
  catalogdbSec:
    container_name: catalogdbSec
    environment:
      - POSTGRES_USER=postgressec
      - POSTGRES_PASSWORD=postgressec
      - POSTGRES_DB=CatalogDbSecond

    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalogSec:/var/lib/postgessql/data/  